version: 2.1
orbs:
  orb-tools: circleci/orb-tools@8.27.4

workflows:
  lint-pack_validate_publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          requires:
            - orb-tools/pack
          filters:
            branches:
              only:
                - master
          orb-name: rainforest-qa/rainforest
          publish-token-variable: CIRCLE_ORG_ADMIN_TOKEN

  release:
    jobs:
      - orb-tools/pack:
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /^v\d+\.\d+\.\d+$/
      - orb-tools/publish:
          filters:
            tags:
              only:
                - /^v\d+\.\d+\.\d+$/
          requires:
            - orb-tools/pack
          orb-ref: rainforest-qa/rainforest@${CIRCLE_TAG:1}
          publish-token-variable: CIRCLE_ORG_ADMIN_TOKEN
