version: 2.1
orbs:
  cli: circleci/circleci-cli@0.1.5
  orb-tools: circleci/orb-tools@8.27.4

jobs:
  validate_orb:
    executor: cli/default
    steps:
      - checkout
      - orb-tools/validate:
          orb-path: src/orb.yml

workflows:
  btd:
    jobs:
      - validate_orb:
        filters:
          branches:
            ignore:
              - master

      - orb-tools/publish-dev:
          filters:
            branches:
              only:
                - master
          checkout: true
          orb-name: rainforest-qa/rainforest
          orb-path: src/orb.yml
          validate: true

      - orb-tools/publish:
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /^\d+\.\d+\.\d+$/
          orb-path: src/orb.yml
          orb-ref: rainforest-qa/rainforest@${CIRCLE_TAG}
          validate: true
