version: 2.1
orbs:
  orb-tools: circleci/orb-tools@2.0.0

workflows:
  btd:
    jobs:
      - orb-tools/validate:
        filters:
          branches:
            except:
              - master
      - orb-tools/publish:
          filters:
            branches:
              only:
                - master
            tags:
              only:
                - /^\d+\.\d+\.\d+$/
          orb-path: src/orb.yml
          orb-ref: rainforest-qa/rainforest@${CIRCLE_TAG}
          validate: true
