version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.0.0
  rf: rainforest-qa/rainforest@<<pipeline.parameters.dev-orb-version>>

parameters:
  dev-orb-version:
    default: 'dev:alpha'
    type: string
  run-integration-tests:
    default: false
    type: boolean

jobs:
  integration-tests-for-your-orb:
    executor: rf/default
    environment:
      TOP_SECRET_TOKEN: 'MY_SECRET_PASSWORD'
      TOP_SECRET_TOKEN_WITH_SPACES: 'MY SECRET PASSWORD'
    steps:
      - rf/install:
          architecture: "386"
      - run:
          name: Is the CLI present, is it from the stable channel
          command: |
            /usr/local/bin/rainforest-cli --skip-update --version | tee /tmp/rf-version
            grep 'stable channel' /tmp/rf-version
      - rf/run_qa:
          dry_run: true
          token: 'TOP_SECRET_TOKEN'
          run_group_id: '123'
      - rf/run_qa:
          dry_run: true
          token: 'TOP_SECRET_TOKEN_WITH_SPACES'
          run_group_id: '123'
      - rf/run_qa:
          dry_run: true
          token: 'TOP_SECRET_TOKEN'
          run_group_id: '123'
          environment_id: '1234'
      - rf/run_qa:
          dry_run: true
          token: 'TOP_SECRET_TOKEN'
          run_group_id: '123'
          environment_id: '1234'
          conflict: abort
      - rf/run_qa:
          dry_run: true
          token: 'TOP_SECRET_TOKEN'
          run_group_id: '123'
          environment_id: '1234'
          conflict: abort-all

workflows:
  integration-tests_prod-release:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - integration-tests-for-your-orb

  lint-pack_validate_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          requires:
            - orb-tools/pack
          orb-name: rainforest-qa/rainforest
          publish-token-variable: CIRCLE_ORG_ADMIN_TOKEN
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          token-variable: CIRCLE_ORG_ADMIN_TOKEN
          requires:
            - orb-tools/publish-dev

  release:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/pack:
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /^v\d+\.\d+\.\d+$/
      - orb-tools/publish:
          filters:
            tags:
              only:
                - /^v\d+\.\d+\.\d+$/
          requires:
            - orb-tools/pack
          attach-workspace: true
          orb-ref: rainforest-qa/rainforest@${CIRCLE_TAG:1}
          publish-token-variable: CIRCLE_ORG_ADMIN_TOKEN
