version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.0.0
  rf: rainforest-qa/rainforest@<<pipeline.parameters.dev-orb-version>>

parameters:
  dev-orb-version:
    default: dev:alpha
    type: string
  run-integration-tests:
    default: false
    type: boolean

jobs:
  integration-tests-for-your-orb:
    executor: rf/default
    environment:
      TOP_SECRET_TOKEN: 'MY_SECRET_PASSWORD'
      TOP_SECRET_TOKEN_WITH_SPACES: 'MY SECRET PASSWORD'
    steps:
      - run: apk add curl jq wget
      - rf/install:
          architecture: "386"
          version: v2.22.3
      - run:
          name: Is the CLI present, is it at the requested version
          command: |
            /usr/local/bin/rainforest --skip-update --version | tee /tmp/rf-version
            grep '2.22.3' /tmp/rf-version
      - rf/install:
          architecture: "386"
      - run:
          name: Is the CLI present, is it at the latest version
          command: |
            /usr/local/bin/rainforest  --skip-update --version | tee /tmp/rf-version
            /usr/local/bin/rainforest update
            /usr/local/bin/rainforest  --skip-update --version | tee /tmp/rf-updated-version
            diff /tmp/rf-version /tmp/rf-updated-version
      - rf/run_qa:
        # Check run group validation
          dry_run: true
          token: 'TOP_SECRET_TOKEN'
          run_group_id: '123'
          pipeline_id: << pipeline.id >>
      - rf/run_qa:
        # Validate tokens with spaces in without blowing up
          dry_run: true
          token: 'TOP_SECRET_TOKEN_WITH_SPACES'
          run_group_id: '123'
          pipeline_id: << pipeline.id >>
      - rf/run_qa:
        # Check environment_id is validated
          dry_run: true
          token: 'TOP_SECRET_TOKEN'
          run_group_id: '123'
          environment_id: '1234'
          pipeline_id: << pipeline.id >>
      - rf/run_qa:
        # Check conflict with cancel is validated
          dry_run: true
          token: 'TOP_SECRET_TOKEN'
          run_group_id: '123'
          conflict: cancel
          pipeline_id: << pipeline.id >>
      - rf/run_qa:
        # Check conflict with cancel-all is validated
          dry_run: true
          token: 'TOP_SECRET_TOKEN'
          run_group_id: '123'
          conflict: cancel-all
          pipeline_id: << pipeline.id >>

workflows:
  integration-tests_prod-release:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - integration-tests-for-your-orb

  lint-pack_validate_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          requires:
            - orb-tools/pack
          orb-name: rainforest-qa/rainforest
          publish-token-variable: CIRCLE_ORG_ADMIN_TOKEN
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          token-variable: CIRCLE_ORG_ADMIN_TOKEN
          requires:
            - orb-tools/publish-dev

  release:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/pack:
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /^v\d+\.\d+\.\d+$/
      - orb-tools/publish:
          filters:
            tags:
              only:
                - /^v\d+\.\d+\.\d+$/
          requires:
            - orb-tools/pack
          attach-workspace: true
          orb-ref: rainforest-qa/rainforest@${CIRCLE_TAG:1}
          publish-token-variable: CIRCLE_ORG_ADMIN_TOKEN
